apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeflux
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
    spec:
      serviceAccountName: kubeflux
      containers:
        - image: quay.io/cmisale1/kubeflux-sidecar:dev
          imagePullPolicy: Always
          command:
          - /go/src/kubeflux/bin/server
          name: kubeflux-sidecar
        - image: localhost:5000/scheduler-plugins/kube-scheduler:latest
          imagePullPolicy: Always
          command:
          - /bin/kube-scheduler
          - --leader-elect=false
          - --config=/home/scheduler-config.yaml
          - -v=9
          name: kubeflux
          volumeMounts:
          - mountPath: /home
            name: kubeflux-scheduler-config-vol
          securityContext:
            privileged: false
      hostNetwork: false
      hostPID: false
      volumes:
      - configMap:
          name: kubeflux-scheduler-config
        name: kubeflux-scheduler-config-vol
